<a href="https://colab.research.google.com/github/BiradarSonali/Sonali-Biradar/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/IMDB Dataset.csv')

In [ ]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
data['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [ ]:
data.shape

(50000, 2)

In [ ]:
data['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [ ]:
import re
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)
remove_html_tags(data['review'][1])

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [ ]:

data['review']=data['review'].apply(remove_html_tags)
data['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...                        
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [ ]:
def remove_url(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)
text1='Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2='Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'
text3='Google search here www.google.com'
text4='For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'
remove_url(text1)

'Check out my notebook '

In [ ]:
import string
import time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude=string.punctuation

In [ ]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
  return text
text='string.With.Punctuation?'
remove_punc(text)

'stringWithPunctuation'

In [ ]:
def remove_punc(text):
  return text.translate(str.maketrans('','',exclude))
text='string.With.Punctuation?'
remove_punc(text)

'stringWithPunctuation'

In [ ]:
data['review'].apply(remove_punc)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production The filming tech...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...                        
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [ ]:
chat_words={ "AFAIK": "As far as I know",
      "AFK": "Away from keyboard",
      "ASAP": "As soon as possible",
      "ATK": "At the keyboard",
      "ATM": "At the moment",
      "BRB": "Be right back",
      "BTW": "By the way",
      "CU": "See you",
      "CUL8R": "See you later",
      "CYA": "See ya",
      "FAQ": "Frequently asked questions",
      "FC": "Fingers crossed",
      "FWIW": "For what it's worth",
      "FYI": "For your information",
      "GAL": "Get a life",
      "GG": "Good game",
      "GN": "Good night",
      "GMTA": "Great minds think alike",
      "GR8": "Great",
      "G9": "Genius",
      "IC": "I see",
      "IDK": "I don't know",
      "ILU": "I love you",
      "IMHO": "In my humble opinion",
      "IMO": "In my opinion",
      "IOW": "In other words",
      "IRL": "In real life",
      "KISS": "Keep it simple, stupid",
      "LDR": "Long distance relationship",
      "LMAO": "Laughing my ass off",
      "LOL": "Laughing out loud",
      "LTNS": "Long time no see",
      "L8R": "Later",
      "MTE": "My thoughts exactly",
      "M8": "Mate",
      "NRN": "No reply necessary",
      "OIC": "Oh I see",
      "OMG": "Oh my god",
      "PITA": "Pain in the ass",
      "PRT": "Party",
      "ROFL": "Rolling on the floor laughing",
      "RIP": "Rest in peace",
      "SMH": "Shaking my head",
      "SYS": "See you soon",
      "TBA": "To be announced",
      "TBC": "To be continued",
      "TFTI": "Thanks for the info",
      "THX": "Thank you",
      "TTYL": "Talk to you later",
      "U": "You",
      "W8": "Wait",
      "WTF": "What the fuck",
      "WTG": "Way to go",
      "WUF": "Where are you from",
      "YOLO": "You only live once"}
def chat_conversion(text):
  new_text=[]
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return ' '.join(new_text)
chat_conversion("WTF")

'What the fuck'

In [ ]:
from textblob import TextBlob

In [ ]:
incorrect_text='ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'
textBlb=TextBlob(incorrect_text)
textBlb.correct().string

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def remove_stopwords(text):
  new_text=[]
  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)
  x=new_text[:]
  new_text.clear()
  return ' '.join(x)

In [ ]:
remove_stopwords('probably my all-time favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 3 times')

'probably  all-time favorite movie  story  selflessness sacrifice  dedication   noble cause    preachy  boring   never gets old despite   seen   3 times'

In [ ]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
data['review'].apply(remove_stopwords)

KeyboardInterrupt: 

In [ ]:
def remove_emoji(text):
   emoji_pattern = re.compile('['u"\U0001F600-\U0001F64F"
                           u"\U0001F300-\U0001F5FF"
                           u"\U0001F680-\U0001F6FF"
                           u"\U0001F1E0-\U0001F1FF"
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"']+',flags=re.UNICODE)
   return emoji_pattern.sub(r'',text)

In [ ]:
remove_emoji('Loved the movie. It was 😘😘')

'Loved the movie. It was '

In [ ]:
remove_emoji('I am Happy 😊')

'I am Happy '

In [ ]:
remove_emoji('Lmao  😂 😂 😂')

'Lmao    '

In [ ]:
!pip install emoji
import emoji
print(emoji.demojize('Python is 🔥'))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 586.9/586.9 kB 7.5 MB/s eta 0:00:00
Python is :fire:


In [ ]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:


In [ ]:
sent1='I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
sent2='I am going to delhi.I will stay there for 3 days.Lets hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 'I will stay there for 3 days',
 'Lets hope the trip to be great']

In [ ]:
sent3='I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [ ]:
tokens=re.findall('[\w]+',sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
text='''I am going to delhi!
I will stay there for 3 days.
Lets hope the trip to be great'''
sent=re.compile('[.!?]').split(text)
sent

['I am going to delhi',
 '\nI will stay there for 3 days',
 '\nLets hope the trip to be great']

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
sent1='I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [ ]:
sent_tokenize(text)

['I am going to delhi!',
 'I will stay there for 3 days.',
 'Lets hope the trip to be great']

In [ ]:
sent5='I have a Ph.D in A.I'
sent6="We're here to help you! mail me the details."
sent7='A 5km ride cost $10.50'
print(word_tokenize(sent5))
print(word_tokenize(sent6))
print(word_tokenize(sent7))

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']
['We', "'re", 'here', 'to', 'help', 'you', '!', 'mail', 'me', 'the', 'details', '.']
['A', '5km', 'ride', 'cost', '$', '10.50']


In [ ]:
import spacy
nlp=spacy.load('en_core_web_sm')
doc1=nlp(sent5)
doc2=nlp(sent6)
doc3=nlp(sent7)
doc4=nlp(sent1)
for token in doc1:
  print(token)

I
have
a
Ph
.
D
in
A.I


In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps=PorterStemmer()
def stem_words(text):
  return ' '.join([ps.stem(word) for word in text.split()])
sample='walk walks walking walked'
stem_words(sample)

'walk walk walk walk'

In [ ]:
stem_words(data['review'][1])

'a wonder littl production. the film techniqu is veri unassuming- veri old-time-bbc fashion and give a comforting, and sometim discomforting, sens of realism to the entir piece. the actor are extrem well chosen- michael sheen not onli "ha got all the polari" but he ha all the voic down pat too! you can truli see the seamless edit guid by the refer to williams\' diari entries, not onli is it well worth the watch but it is a terrificli written and perform piece. a master product about one of the great master\' of comedi and hi life. the realism realli come home with the littl things: the fantasi of the guard which, rather than use the tradit \'dream\' techniqu remain solid then disappears. it play on our knowledg and our senses, particularli with the scene concern orton and halliwel and the set (particularli of their flat with halliwell\' mural decor everi surface) are terribl well done.'

In [ ]:

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
wordnet_lemmatizer=WordNetLemmatizer()

sentence='He was running and eating at same time.He has bad habit of swimming after playing long hours in the Sun.'
punctuations='?:!.,;'
sentence_words=nltk.word_tokenize(sentence)
for word in sentence_words:
  if word in punctuations:
    sentence_words.remove(word)
sentence_words
print('{0:20}{1:20}'.format('Word','Lemma'))
for word in sentence_words:
  print('{0:20}{1:20}'.format(word,wordnet_lemmatizer.lemmatize(word)))

[nltk_data] Downloading package wordnet to /root/nltk_data...


Word                Lemma               
He                  He                  
was                 wa                  
running             running             
and                 and                 
eating              eating              
at                  at                  
same                same                
time.He             time.He             
has                 ha                  
bad                 bad                 
habit               habit               
of                  of                  
swimming            swimming            
after               after               
playing             playing             
long                long                
hours               hour                
in                  in                  
the                 the                 
Sun                 Sun                 


In [ ]:
import numpy as np

In [ ]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,3))

In [ ]:
bow=cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]


In [ ]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1]])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']


In [ ]:
# Apply all the preprocessing techniques that you think are necessary


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
temp_df=pd.read_csv('IMDB Dataset.csv')
df=temp_df.iloc[:10000]
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

17

In [ ]:
df.drop_duplicates(inplace=True)

<ipython-input-14-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [ ]:
df.duplicated().sum()

0

In [ ]:
import re
def remove_tags(text):
  cleaned_text=re.sub(re.compile('<.*?>'),'',text)
  return cleaned_text

In [ ]:
df['review']=df['review'].apply(remove_tags)

<ipython-input-18-16f7647403ce>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)


In [ ]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [ ]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x: ' '.join(x))


LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
